### ISSUE TITLE
Can the 9.2 (ZM) currencies be added?

### ISSUE THREAD

**Issue by Loredrin** [wow-addon/Broker_CurrencyFlow#19]
Wondering if the 9.2 currencies could be added?

1979  Cyphers of the First Ones
 2009  Cosmic Flux

**Comment by yoshimo** [comment]
#18 , duplicate

**Comment by davidcraig** [comment]
Done

**Comment by Loredrin** [comment]
Not seeing the update you posted with the ZM currencies added. The download is still showing as 1.8.6 from November.

**Comment by davidcraig** [comment]
@Loredrin which updater you using?

**Comment by davidcraig** [comment]
Not sure why curse hasn't picked up the addon version, but i've added it to wago: https://addons.wago.io/addons/broker-currencyflow - wowup should hopefully pick this up.

**Comment by Loredrin** [comment]
I use Curseforge for most of my addons. But do use wowup for some as well. Will grab it from wago. Thanks!

**Comment by Loredrin** [comment]
Wago is not showing it either (the app) the Wago website has a page for it. but it is blank (no download available). No luck on Wowup either.

**Comment by davidcraig** [comment]
Wago declined as the folder inside the github generated zip file was Broker_CurrencyFlow-1.8.7 - so have fixed this with a new upload, hopefully it shows up soon, if not it'll take a little longer as i'm not online this evening.
